name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
      # id per usare lo step in altri punti
        id: greet
      # per indicare quali actions usare presenti su github
      # non conviene selezionare il branch (tipo @master) ma il commit o la versione per evitare breaking changes
        uses: ./actions/hello-world-javascript-action@2b62cf098444fa7c3765a96fc337e8ba42fa9c04
        with:
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"